accounts/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('signup/', views.signup, name='accounts.signup'),
    path('login/', views.login, name='accounts.login'),
    path('logout/', views.logout, name='accounts.logout'),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home.index'),
    path('about', views.about, name='home.about'),
]

jobgenie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('profiles/', include('profiles.urls')),
    path('accounts/', include('accounts.urls')),
    path('jobs/', include('jobs.urls')),
    path('recruiters/', include(('recruiters.urls', 'recruiters'), namespace='recruiters')),
]
handler403 = "django.views.defaults.permission_denied"

recruiters/urls.py
from django.urls import path
from .views import (
    RecruiterSignupView, RecruiterDashboardView, BecomeRecruiterView,
    update_status, RecruiterApplicationDetailView, CandidateSearchView
)

app_name = "recruiters"

urlpatterns = [
    path("signup/", RecruiterSignupView.as_view(), name="signup"),
    path("dashboard/", RecruiterDashboardView.as_view(), name="dashboard"),
    path("candidates/", CandidateSearchView.as_view(), name="candidate_search"),
    path("become/", BecomeRecruiterView.as_view(), name="become_recruiter"),
    path("update_status/<int:app_id>/<str:new_status>/", update_status, name="update_status"),
    path("application/<int:pk>/", RecruiterApplicationDetailView.as_view(), name="application_detail"),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms.utils import ErrorList
from django.utils.safestring import mark_safe
from django import forms
from profiles.models import UserProfile
from django.contrib.auth.models import User

class CustomErrorList(ErrorList):
 def __str__(self):
    if not self:
        return ''
    return mark_safe(''.join([ f'<div class="alert alert-danger" role="alert"> {e}</div>' for e in self]))

class BootstrapRadioSelect(forms.RadioSelect):
    template_name = 'django/forms/widgets/radio.html'
    option_template_name = 'django/forms/widgets/radio_option.html'

    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        for option in context['widget']['optgroups'][0][1]:
            option['attrs']['class'] = 'form-check-input'
        return context


class CustomUserCreationForm(UserCreationForm):
    ROLE_CHOICES = (
    ('JOB_SEEKER', 'Job Seeker'),
    ('RECRUITER', 'Recruiter'),
    )

    role = forms.ChoiceField(
    choices=ROLE_CHOICES,
    widget=forms.RadioSelect,
    required=True
    )
    


    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'password1', 'password2', 'role')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None
            self.fields[fieldname].widget.attrs.update({'class': 'form-control'})

    def save(self, commit=True):
        user = super().save(commit=commit)

    # Get the selected role from the form
        role = self.cleaned_data.get('role')

    # Create or update the UserProfile
        from profiles.models import UserProfile
        profile, created = UserProfile.objects.get_or_create(user=user)
        profile.role = role
        profile.save()

    # If recruiter, create recruiter profile
        if role == 'RECRUITER':
            from recruiters.models import Recruiter
            Recruiter.objects.get_or_create(user=user)
        return user

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomErrorList
from django.contrib.auth import login as auth_login, authenticate, logout as auth_logout
from django.contrib.auth.decorators import login_required
from profiles.models import UserProfile
from recruiters.models import Recruiter
# Create your views here.
@login_required
def logout(request):
    auth_logout(request)
    return redirect('home.index')

def signup(request):
    template_data = {}
    template_data['title'] = 'Sign Up'
    next_url = request.GET.get('next') or request.POST.get('next') or 'home.index'
    if request.method == 'GET':
        template_data['form'] = CustomUserCreationForm()
        return render(request, 'accounts/signup.html', {'template_data': template_data})
    elif request.method == 'POST':
        form = CustomUserCreationForm(request.POST, error_class=CustomErrorList)
        if form.is_valid():
            user = form.save()
            # Redirect to login page instead of auto-login
            return redirect('accounts.login')
        else:
            template_data['form'] = form
            return render(request, 'accounts/signup.html',
            {'template_data': template_data})

def login(request):
    template_data = {}
    template_data['title'] = 'Login'
    template_data['next'] = request.GET.get('next', '')
    if request.method == 'GET':
        return render(request, 'accounts/login.html',{'template_data': template_data})
    elif request.method == 'POST':
        user = authenticate(
        request,
        username = request.POST['username'],
        password = request.POST['password']
        )
        next_url = request.POST.get('next') or 'home.index'
        if user is None: 
            template_data['error'] ='The username or password is incorrect.'
            return render(request, 'accounts/login.html',{'template_data': template_data})
        else:
            auth_login(request, user)
            return redirect(next_url)
        

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<div class="p-3 mt-4">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card shadow p-3 mb-4 rounded">
                    <div class="card-body">
                        <h2>Login</h2>
                        <hr />
                        {% if template_data.error %}
                            <div class="alert alert-danger" role="alert">
                                {{ template_data.error }}
                            </div>
                            {% endif %}
                            <form method="POST">
                                <input type="hidden" name="next" value="{{ template_data.next }}">
                                {% csrf_token %}
                                <p>
                                    <label for="username">Username</label>
                                    <input id="username" type="text"
                                    name="username" required
                                    autocomplete="username"
                                    class="form-control">
                                </p>
                                <p>
                                    <label for="password">Password</label>
                                    <input id="password" type="password"
                                    name="password" required
                                    autocomplete="current-password"
                                    class="form-control">
                                </p>
                                <div class="text-center">
                                    <button type="submit" class="btn bg-dark text-white">Login</button>
                                </div>
                            </form>
                            <p>Don't have an account? 
                                <a href="{% url 'accounts.signup' %}?next={% url 'recruiters:signup' %}">Sign up here</a>
                            </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="p-3 mt-4">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card shadow p-3 mb-4 rounded">
          <div class="card-body">
            <h2>Sign Up</h2>
            <hr />
            <form method="POST">
              <input type="hidden" name="next" value="{{ template_data.next }}">
              {% csrf_token %}
              {{ template_data.form.as_p }}
              <button type="submit" class="btn bg-dark text-white">
                Sign Up
              </button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}